### ISSUE TITLE
Double-check listening treatments implementation

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#314]
In discussion with @NettaWeinstein, we have decided to try four treatment conditions:
1. Short listening training
2. Short listening-in-motion training
3. Short speaking training
4. No training, just discussion

I've implemented these as described in this file: https://github.com/Watts-Lab/deliberation-empirica/blob/main/.empirica/treatments.weinstein.yaml

This file has each condition defined with a particular set of attributes:
```yaml
treatments:
  - name: Weinstein Listening In Motion Condition
    desc: One 13 minute video
    factors:
      playerCount: 2
      gameStages:
        - name: Intro
          type: prompt
          prompt:
            - weinstein_listening/intro_videos.md
          duration: 45
        - name: Video - How to listen in motion
          type: video
          url: https://youtu.be/FNcG-OtPpJU
        - name: Attention Check Quiz
          type: prompt
          duration: 120
          prompt:
            - weinstein_listening/motion_expert.md
            - weinstein_listening/motion_technique.md
            - weinstein_listening/motion_strategies.md
        - name: Reflect on Rejection
          type: prompt
          duration: 120
          prompt:
            - weinstein_listening/reflect_rejection.md
        - name: Discussion
          type: discussion
          prompt: weinstein_listening/topic_rejection.md
          duration: 600
      exitSurveys:
        - ListeningQualityPartner
        - ListeningQualityOwn
        - AutonomyNeedSatisfaction
        - LonelinessSingleItem
        - Demographics
```

- `name` gives the treatment name as it will show up in the admin console
- `desc` is purely for documentation
- `playerCount` is the number of people who will participate in each "game" (including treatments and discussion)
- `gameStages` shows the progression that participants will take after the consent, intro screen, and video check
- `exitSurveys` shows the ordered list of surveys that will be shown to participants. (These surveys are implemented and described here: https://github.com/Watts-Lab/surveys/tree/main/surveys, although this is a bit hard to read.)

Within the `gameStages`, each stage of the game has a variety of attributes
- `name` is mostly descriptive and for tracking data after the experiment
- `type` indicates which components will be displayed, and can take the following values:
    - `prompt` displays text or a set of questions to the participant
    - `video` displays a video to the participant
    - `discussion` shows the videocall window and also a discussion prompt/question
- `duration` is the maximum length of the stage in seconds. It defaults to just over 30 minutes. 
    - For video stages, when the video has completed for all players the stage will automatically advance, so we don't need to supply a duration. 
    - For prompt stages, participants may click "next" when they have finished answering the questions, and so proceed to the next stage automatically
    - Discussion stages will always last for the time specified in "duration".
- `url` is the youtube URL of the video to be displayed
- `prompt` can take a list of prompts to be displayed on the same page. 

The prompts are referred to by their directory and filename in this repository folder: https://github.com/Watts-Lab/deliberation-topics/tree/main/topics. If you browse the folder structure on GitHub, you should be able to see the topics rendered basically as they will be seen by the participant. The participant won’t see the metadata at the top of the file, or the line separating the prompt from the responses.

This set of treatments is live on the deliberation server. It would be a good idea to walk through each of the treatments with an in-house team to make sure that everything is implemented correctly and as we expect. Particularly good to check are:

- Is each video link correct for the treatment condition?
- Are the text prompts and questions correct? (I made a few changes to the text prompts, are these ok?)
  - are they spellchecked/formatted properly?
- Is the timing of each stage appropriate?
