### ISSUE TITLE
Timer component for display

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#391]
Add a timer as a component.

- Separate start time and stop time
- If not specified, default to the show time and hide time
- If those arent specified, default to the full stage time

Using this package:
- https://www.npmjs.com/package/react-sweet-progress

![Image](https://user-images.githubusercontent.com/4304478/211614123-9172ddc3-00ce-4b25-aa63-600a9f23b750.png)

- Use a linear progress bar
- Digital time remaining
- Custom warning time
- After time elapses, just sit with the completed progress bar and 0:00

```yaml
elements:
  - type: timer
     displayTime: 0
     hideTime: 60
     startTime: 0
     stopTime: 30
     warnTimeRemaining: 10 
```
