### ISSUE TITLE
Implement treatments where participants in the same game see different things

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#392]

**Comment by JamesPHoughton** [comment]
Players are assigned a "position" in the game based on some attribute. Currently implemented a random assignment. Positions are indexed `0, 1, ...`. Elements can take an attribute that allows them to be displayed to certain positions (and hidden from others), or hidden from certain positions (and shown to others)

```yaml
         elements: 
            - type: prompt
              file: example/youHaveTheFloor.md
              showToPositions: 
                - 1
              displayTime: 60
              hideTime: 120
            - type: prompt
              file: example/youDoNotHaveTheFloor.md
              hideFromPositions:
                - 1
              displayTime: 60
              hideTime: 120
```
