### ISSUE TITLE
seperator line component for display

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#393]
Lets use syntax like this:
```yaml
              - type: prompt
              file: policing_2022/leader_floor.md
              showToPositions:
                - 0
              displayTime: 30
              hideTime: 60
            - type: separator <--- this line
            - type: prompt
              file: policing_2022/nonleader_nofloor.md
              hideFromPositions:
                - 0
              displayTime: 30
              hideTime: 60
```
put the horizontal line in a div with a `data-test=` attribute to assist with cypress testing.
