### ISSUE TITLE
Update treatments format to allow more flexible components

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#394]
Currently, there are a finite number of types of stage (video, prompt, discussion) that have fixed layouts. The prompts can be timed, and have sounds associated with them.

```yaml
     gameStages:
        - name: Intro
          type: prompt
          prompt:
            - weinstein_listening/intro_videos.md
          duration: 45
        - name: Video - How to listen in motion
          type: video
          url: https://youtu.be/FNcG-OtPpJU
        - name: Attention Check Quiz
          type: prompt
          duration: 120
          prompt:
            - weinstein_listening/motion_expert.md
            - weinstein_listening/motion_technique.md
            - weinstein_listening/motion_strategies.md
```

```yaml
          prompt:
            - file: policing_2022/persistent_instructions.md
            - file: policing_2022/first_speaker_instructions.md
              displayTime: 0
              hideTime: 60
            - file: policing_2022/group_free_discussion.md
              displayTime: 60
              hideTime: 180
              startDing: true
            - file: policing_2022/structured_discussion_persistent_instructions.md
              displayTime: 180
              hideTime: 930
              startDing: true
            - file: policing_2022/new_discussion_question_header_funding.md
              displayTime: 210
              hideTime: 390
              startDing: true
```

However, we could simplify this and make it more flexible by making video, audio, text prompts, polls, slideshows, etc. all as separate components that can be composed to make a page.

At this point, probably we want to just have one "discussion" or "videoCall" component per stage, rather than making this a composable component itself. 

```yaml
      gameStages:
        - name: Intro
          duration: 45
         chat: false
          components:
            - type: prompt
              file: weinstein_listening/intro_videos.md
              displayTime: 0
              hideTime: 30
           - type: poll
              file: mypoll.md
        - name: Main Discussion
          duration: 45
          showDiscussion: true
          components:
            - type: prompt
              file: weinstein_listening/intro_videos.md
              displayTime: 0
              hideTime: 30
           - type: poll
              file: mypoll.md
```

**Comment by JamesPHoughton** [comment]
Add the ability to select who sees something
```yaml
         elements: 
            - type: prompt
              file: example/youHaveTheFloor.md
              showToPlayersIndex: 
                - 1
              displayTime: 60
              hideTime: 120
            - type: prompt
              file: example/youDoNotHaveTheFloor.md
              showToPlayerIndex: 
                - 0
                - 2
              hideFromPlayerIndex:
                - 1
              displayTime: 60
              hideTime: 120
```
