### ISSUE TITLE
🤷‍♂️ Templating syntax for treatment definitions

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#448]
Most of our treatment definitions are going to be almost identical, with changes in just a few places to differentiate one condition from another.

We should be able to write a treatment template that abstracts those changes, and parameterize them. For instance, we could have a templates section:

```yaml

templates:
  - name: general_outline
    desc: 
    factors:
      playerCount: 1
      gameStages:
       - name: Qualtrics Intervention
          duration: 600
          elements:
            - type: qualtrics
               url: https://upenn.co1.qualtrics.com/jfe/form/SV_czNcL28CkElpBcO/?treatment=${qualtricsTreatment}
        - name: Prompts
          duration: 30
          chatType: video
          elements:
            - projects/example/{discussionPrompt}.md
            - type: submitButton
        - name: Survey Library
          duration: 30
          elements:
            - type: survey
              surveyName: ExampleSurvey
      exitSurveys:
        - LonelinessSingleItem
```

Then our treatments could still be listed individually, but populate a template:

```yaml
treatments:
  - name: T1A
    template: general_outline
    fields:
      - qualtricsTreatment: "ContactProject"
      - discussionPrompt: "urban_unrest"
  - name: T1B
    template: general_outline
    fields:
      - qualtricsTreatment: "ContactProject"
      - discussionPrompt: "ban_assault_rifles"

```

Would also be interesting to be able to programmatically create treatments by 

```yaml
broadcast:
  - broadcastMethod: cross
    template: general_outline
    fields:
    - qualtricsTreatment
      - ContactProject
      - MisperceptionDemocratic
      - ..
    - discussionPrompt
      - "urban_unrest"
      - "ban_assault_rifles"
      - ...
```

**Comment by JamesPHoughton** [comment]
YAML includes some syntax for reusing objects.  (See: https://smcleod.net/2022/11/yaml-anchors-and-aliases/, https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/)
## Anchors + Aliases
```yaml
referencedObject: &ref-obj
  nested1: "hi"
  nested2: "peter"
  
reuserObject:
  reuse: *ref-obj
  otherStuff:
    - "hi"
    - "Lizzy"

```

gets interpreted as:
```yaml
referencedObject: &ref-obj
  nested1: "hi"
  nested2: "peter"
  
reuserObject:
  reuse: 
    nested1: "hi"
    nested2: "peter"
  
  otherStuff:
    - "hi"
    - "Lizzy"
```

## Merge keys
Merge keys work like aliases but let you add elements to an object instead of just replicating the object as a nested object:
```yaml
referencedObject: &ref-obj
  nested1: "hi"
  nested2: "peter"
  
reuserObject:
  <<: *ref-obj
  otherStuff:
    - "hi"
    - "Lizzy"
```
becomes:
```yaml
referencedObject: &ref-obj
  nested1: "hi"
  nested2: "peter"
  
reuserObject:
  nested1: "hi"
  nested2: "peter"
  otherStuff:
    - "hi"
    - "Lizzy"
```

This doesn't do exactly what we want, though, in that it lets us use a subElement multiple times within a container element, or within multiple container elements, but doesn't let us fill in a container element multiple times with different subElements, which is what we will want to do if we are going to make a template of a treatment, and modify it in small ways by substituting in sets of values.

**Comment by JamesPHoughton** [comment]
We will probably need to build up a custom substitution for this, so that we can handle the above cases. We could do the substitutions directly in yaml syntax, but we run into problems due to the nested indent syntax in YAML being important for parsing. This means we'll have to read to JSON first, and then do the substitution. Can probably do this with zod.

In this case, we need a syntax for a placeholder that won't interact negatively with yaml. We can't use `{{ key }}`, as yaml will interpret the curly braces as a dictionary object. We could either choose some syntax that yaml won't try to interpret, for example, `${ key }`, or we could put the double curly braces in quotes `"{{ key }} ". Using quotes has the advantage that we can use a syntax that is common in a lot of other templating frameworks. 

What we choose may depend on how we want to use the keys. I think we're more likely to want to substitute out entire elements of the yaml, rather than just sections of a string, as the strings all refer to specific, discrete items.

**Comment by JamesPHoughton** [comment]
in addition to straight substitution, also want to be able to broadcast across arrays of field values, for instance, if we wanted to create every treatment condition pairing age and gender combinations for player 1 and player 2 (ie. 2 genders * 10 age groups).



# Draft syntax:
- Add a section to the top of the YAML file called `templates` containing a list of templates. Multiple templates can be specified, in any order.
- Each template has a unique `templateName` that is used to reference the template, and persists in the created treatment object
- Each template has a `templateDesc` that includes any notes applied to the template itself
- Templates each represent an object that can be inserted into the rest of the treatment file anywhere - as a treatment, as a stage or piece of treatment, anywhere that an object can sit. Templates can include other templates as components.
- Templates have fields that can be filled in. The fields are denoted by `${ fieldKey }`. Fields are optional, and so a template can just be a reusable chunk of description.
- Choose not to allow default values for fields, to make sure that every choice is explicitly made, and a researcher can't make a mistake by forgetting to fill a field. If they do, it will throw an error message.
- You can use a template in a treatment (or intro-sequence) description by creating an object at any point in the treatment definition. The object must have at least the key "template", with value referring to the intended template's `templateName`.
- To use the template once, the template reference should also have a key "fields", containing a list of `fieldKey: value` pairs. fieldKeys correspond to the template fields in the chosen template, eg, ${ fieldKey }. 
- The template can also be used to broadcast over one or more arrays of field values, in which case the template description will be replaced with a list of filled templates. To do so, include alongside the template reference a "broadcast" object. This object will contain one entry for each dimension you wish to broadcast over, named `d0`, `d1`, etc. Each dimension itself contains a list of objects, each of these objects containing `fieldKey: value` pairs for substituting into a template. 
- You can use the "fields" and the "broadcast" keys together. Values set in `fields` will be applied for all instances of the template generated by this object. Values set in "broadcast" will be applied according to the broadcast rules. If a field is set in both `broadcast` and `fields`, the value in `broadcast` will be used. if a field is set in multiple broadcast dimensions, the value in the lowest numbered dimension will be used. If a field is not set using either the `fields` or `broadcast` options, an error will be thrown.

- A template that uses another template as part of its description can defer specifying a value for a field in the nested template, so long as one of the outer scope templates specifies the field value. All values must be populated by the "treatment" or "introSequence" level, otherwise an error is thrown.
- Templates are expanded after the YAML is loaded as JSON, but before validation. The full treatment description must validate. 

### Example Templates:
In this example, two templates are defined. The first is used to create a game stage, and the second is used to create an entire treatment description. The second uses the first several times to define its stages.
```yaml
templates:
  - templateName: stageTemplate
    templateDesc: replaces an entire stage
    name: ${name}
    duration: ${duration}
    elements:
      - type: prompt
        file: projects/example/multipleChoice.md
        name: ${promptName}
      - type: separator
        style: ${separatorStyle | "thin"}
      - type: submitButton
      
  - templateName: basicTreatmentTemplate
    templateDesc: replaces an entire treatment
    name: ${name}
    desc: ${desc}
    playerCount: 2
    groupComposition:
      - position: 0
        conditions:
          - reference: prompt.introMultipleChoiceWizards
            comparator: isOneOf
            value: ${p0_introMultipleChoiceWizardsValues}

      - position: 1
        conditions:
          - reference: prompt.introMultipleChoiceWizards
            comparator: equals
            value: ${p1_introMultipleChoiceWizardsValue}

    gameStages:
      - template: stageTemplate
        fields:
          name: Opinion Survey 1
          duration: 30
          promptName: Response 1

      - template: stageTemplate
        fields:
          name: Opinion Survey 2
          duration: 30
          promptName: Response 2
```



```yaml
      - template: stageTemplate
        fields:
          separatorStyle: 40        
        broadcast:
          - d0:
            - name: Opinion Survey 3
              promptName: Response 3
            - name: Opinion Survey 4
              promptName: Response 4 
          - d1: 
            - separatorStyle: thin
            - separatorStyle: thick
```

**Comment by JamesPHoughton** [comment]
some terminology:
- We'll use "Template" to refer to the generic structure with unfilled field placeholders.
- We'll use "Template Context" or just "Context" to refer to the object that specifies which template to use, what values to fill in, and how to handle broadcasting
- We'll use "Template Instance" to refer to the filled template containing field values.

**Comment by JamesPHoughton** [comment]
Problem with this syntax for templates is that the template must return an object
```yaml
 - templateName: stageTemplate
    templateDesc: replaces an entire stage
    name: ${name}
    duration: ${duration}
    elements:
      - type: prompt
        file: ${promptFile}
        name: ${promptName}
      - type: submitButton
```

What if we want the template to contain a list, or just a single value?

Instead, lets move the actual contents of the template into a field on the template object:
```yaml
 - templateName: stageTemplate
    templateDesc: replaces an entire stage

    name: ${name}
    duration: ${duration}
    elements:
      - type: prompt
        file: ${promptFile}
        name: ${promptName}
      - type: submitButton
```
