### ISSUE TITLE
Conditionally render components based on submitted values

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#458]
There are several options we could think about for making prompts mandatory. 

# Allow display components to be conditional on the results of other components
First, we could hide the submit button on the page until participants have completed the required questions. This would mean adding some display logic that could look back to previous questions and check that they were answered before continuing. We could actually make the logic quite complex, so that participants have to respond with certain values, or allow subsequent elements to display conditional on which response was selected. We'll need to think through the syntax.

# Add a 'required' tag directly to the question
In this case, we could have the page submit check for any "required" tags and if they aren't answered, show a pop-up message.

**Comment by xehu** [comment]
Elaborating --- Ideally, the user experience should be similar to the "Force Response" and "Answer Validation" options on Qualtrics. In other words, there should be the option to:

- Force the participant to not move on until mandatory questions are answered;
- Force the participant to not move on until mandatory questions are answered *with a specified value* (i.e., in an attention check, the participant responds with the correct answer to confirm they understand the rules).

**Comment by JamesPHoughton** [comment]
Currently we can name prompts and positions and use them in displaying elements. For example, if we define a prompt with a name:
```yaml
elements:
  - type: prompt
    file: projects/example/openResponse.md
    name: openResponseExample1
```

We can use the name and attribute to display the result:
```yaml
elements:
  - type: display
    promptName: openResponseExample1
    position: 1
    showToPositions:
      - 0
```

We should be able to refer to prompts the same way when adding conditionals.
``` yaml
elements:
  - type: prompt
    file: displayWhenConditionMet.md
    conditions:
      - promptName: openResponseExample1
        position: 1
        comparator: lengthGreaterThan
        comparison: 10
```

We could have multiple conditions that all need to be met, but we don't actually want to build up a full nested logical tree here, as it gets too crazy. Having a few constraints on what we say is possible will help simplify the syntax and make it easier to understand what was done. 



### position
Could take:
- `0`, `1`, a position index , 
- `shared` if it is a shared response, 
- `player` to get the current player's response, 
- `all` if every individual needs to meet the condition

### comparator
Taken from the chai assertion syntax: https://www.chaijs.com/api/assert/#method_equal
#### Any prompt type:
- `exists`, `notExists` if we just want to know if the question has an answer
- `equal`, `notEqual`
- `oneOf` comparison is a list of possible options

#### Numerical response type:
- `isAbove`, `isAtLeast`, `isBelow`, `isAtMost`

#### String response type:
- `lengthGreaterThan`, `lengthLessThan` for string responses
- `include`, `notInclude`
- `match`, `notMatch` matches regular expression

#### comparison
- number
- string
- list of numbers or strings



Adding conditionals would let us build up conditions for when a participant could submit a stage, as we could hide a submit button until the participant had either entered a value, or typed a response, etc.
