### ISSUE TITLE
Construct groups based on attributes

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#497]
As a scientist, I want to construct groups with particular characteristics of participants, so that I can measure the effect of different group compositions on deliberation outcomes.

I will get data to construct group compositions from several sources:
1. Surveys conducted in the intro sequence
2. Prompts answered in the intro sequence
3. Surveys or prompts conducted in previous experiments and saved to the player data store
4. Other attributes of players' participation saved to the data store

As the construction of the group is effectively part of the treatment (as it localizes the group at a particular point in the design space) it belongs as part of the experiment treatments definition. One way we could implement this is:

```yaml
- name: cypress_omnibus
    desc: Cypress testing everything possible in one go.
    playerCount: 2
    groupComposition:
      - name: democrat
        position: 0
        conditions:
          - sourceType: survey
            surveyName: PoliticalPartyUS
            result: position
            comparator: lessThan
            value: 0
      - name: republican
        position: 1
        conditions:
          - sourceType: survey
            surveyName: PoliticalPartyUS
            result: position
            comparator: greaterThan
            value: 0
      
    gameStages:
       ...
```
