### ISSUE TITLE
Uniquely name tajriba.json files

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#508]
When we deploy a new version of the app, it is likely that the old version of the tajriba.json file will not work with the new deployment. So, we should name each tajriba.json file with a name that points to which version of the bundle it was created by. This way, we can store multiple versions together, for simplicity.

I think at this point, the best way to do that is to use the date that the container was registered on GHCR as the identifier: 

```yaml
# register_container_image.yaml

...
      - name: Get current date
        run: echo "BUNDLE_DATE=$(date +"%Y_%m_%d_%T")" >> $GITHUB_ENV

      - name: Update empirica.toml
        run: |
          sed -i 's/tajriba.json/tajriba_${{ env.BUNDLE_DATE }}.json/' .empirica/empirica.toml
...

```
