### ISSUE TITLE
Update tajriba.json file name in builder

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#564]
Currently, when a container image is  built, it tries to update empirica.toml before building up the image to include the image tag:

```yaml
 - name: Update empirica.toml
        run: |
          sed -i 's/tajriba.json/tajriba_${{ env.BUNDLE_DATE }}.json/' .empirica/empirica.toml
```

unfortunately, it doesn't work
