### ISSUE TITLE
Deploy to DigitalOcean

### ISSUE THREAD

**Issue by yli12313** [Watts-Lab/deliberation-empirica#58]
The DigitalOcean deployment of Empirica worked after you changed the http port from **8080** -> **3000**; the below configuration file called `stringray-app.yaml` is the correct one:

```
name: stingray-app
region: nyc
services:
- dockerfile_path: Dockerfile
  github:
    branch: james-ngrok-debug
    repo: Watts-Lab/deliberation-empirica
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xs
  name: deliberation-empirica
  routes:
  - path: /
  source_dir: /
```
