### ISSUE TITLE
Add player "title", and make it an option to add to discussion

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#600]
As an experiment designer, I sometimes want to give visible titles to individuals in order to distinguish them visually and set role expectations.

- [ ] Assign a "Title" to a particular position using the group composition argument in the treatment file:
```
    groupComposition:
      - name: A
        position: 0
        displayTitle: "Org. A Representative"
      - name: B
        position: 1
        displayTitle: "Org. B Representative"
      - name: C
        position: 2
        displayTitle: "Org. C Representative"
```

Add an option to display this title after a user's name in:
- [ ] the video call window 
- [ ] text chat
- [ ] a templated markdown file

@xehu, does this description cover your use case?

**Comment by xehu** [comment]
@JamesPHoughton yes, except ideally there may also be an option to _replace_ a user's name with this title. Even if it is not critical in this present study, there may be study designs that require full anonymity, where nicknames that signal gender (e.g., "Emily") should be removed.

So I think V0 (technically easier) would be to _append_ it to the person's nickname.
V1 (for later) would be to _replace_ the person's name as an option.

**Comment by JamesPHoughton** [comment]
Currently we indicate the chat with a single keyword
```yaml
- name: Discussion
  duration: 600
  chatType: video
  elements:
    - ...
```

We could instead make the chat an object:
```yaml
- name: Discussion
  duration: 600
  chat:
    type: video
    showNickname: true
    showTitle: true
  elements:
    - ...
```
