### ISSUE TITLE
Display player responses in other prompts

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#609]
As an experiment designer, I want to be able to take one participant's response to a prompt and display it to other participants in subsequent stages, in a way that is not editable to them

Ideally, I'd be able to do this for:
- prompts:
  - [x] open response questions (individual)
  - [ ] open response questions (shared) 
  - [ ] multiple choice questions
- [ ] surveys
- metadata:
  - [ ] position
  - [ ] nickname

Prompts are saved to the player object according to the name given in the prompt description:
```yaml
- type: prompt
  file: projects/example/multipleChoice.md
  name: multipleChoiceIntroPrompt
```
so, we could fetch those results:

```yaml
- type: display 
  name: multipleChoiceIntroPrompt
  position: 1
```
