### ISSUE TITLE
cypress test multiple conditions

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#627]
Display conditions can take a list:
```
            conditions:
              - promptName: multipleChoiceWizardsIntroExample
                comparator: equal
                value: Merlin
              - promptName: individualMultipleChoiceColors
                comparator: equal
                value: Octarine
```

test that this is implemented correctly.
