### ISSUE TITLE
prompt file shorthand fails in intro steps

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#629]
In the game, you can specify a prompt to just display with no options by just including the filename. We interpret that as just a straight display:

```yaml
    gameStages:
      - name: Topic Survey
        duration: 60
        elements:
          - projects/example/multipleChoice.md
```

This doesn't seem to work in the intro stages, as it doesn't render the component
```yaml
    introSteps:
      - name: Test Prompts In Intro
        elements:
          - projects/example/multipleChoice.md
          - type: submitButton
            buttonText: Continue
```

Todo:
- [x] add a test of this behavior
- [ ] check that it works
