### ISSUE TITLE
Bug in percentAgreement comparisons

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#742]
```
conditions:
      - promptName: test
        position: percentAgreement
        comparator: isAbove
        value: 66
```
should display when 2/3 people agree, but currently does not. Could be that we're miscalculating the percentages.
