### ISSUE TITLE
use non-prompt data in conditions

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#756]
As an experiment designer, I want to be able to display elements condition on other items that the participants have already entered, so that I can make my experiment structure responsive to the user's behavior.

There are a number of data objects that we may want to reference during the experiment in conditional displays and player assignments:
- prompt responses
- survey responses
- responses to qualtrics surveys
- talk meter values
- URL parameters
- country locations, etc
- participant attributes saved from a different time
- number of dispatch attempts

In addition, sometimes we measure these things more than once, ie, we might repeat a survey before and after a discussion.

Currently, our naming convention for saving these pieces of data is a bit all over the place. For a prompt, it could be `prompt_{the name of the object defined in the treatment file}, or `prompt_{progressLabel}_{name from the prompt file if given otherwise the filename itself}`. for surveys, it is `survey_{name of survey}_{progresslabel}`. 

This heterogeneity makes it difficult to confidently refer to saved data values in conditions, etc. We need to come up with a more consistent naming strategy, to simplify this.

**Comment by JamesPHoughton** [comment]
The other way to deal with this is to define a way to get data at different (non-prompt) paths.
Currently we have conditions specified as: 
```yaml
    conditions:
      - promptName: multipleChoiceIntroExample
        comparator: equals
        value: HTML
```

But we could adapt this:
```yaml
    conditions:
      - reference: prompt.specifiedPromptName
        comparator: equals
        value: HTML
```
In this case

```yaml
    conditions:
      - reference: ipInfo.country
        comparator: equals
        value: USA
```

```yaml
    conditions:
      - reference: survey.namedPartySurvey.result.party
        comparator: equals
        value: republican
```
