### ISSUE TITLE
Adding more advanced conditional logic to text entry

### ISSUE THREAD

**Issue by xehu** [Watts-Lab/deliberation-empirica#757]
Sometimes, it's useful to have logic that not only checks the value of a single text box (e.g., the [comparator function](https://github.com/Watts-Lab/deliberation-empirica/blob/74cf1b7e0606f4e49abc5038ebf90f1ea1fcf557/client/src/components/utils.js#L116), but also compares the text box to other text inputs provided by the participant.

For example, suppose that one is [allocating resources to programs](https://github.com/Watts-Lab/task-mapping/blob/master/tasks/summaries/Allocating%20resources%20to%20programs-writeup.md), and there is a fixed amount of resources that the player must allocate.

Then, the inputs across all text boxes must sum to some desired value.

The way to express this relationship in the YAML might look something like the following:
```
promptName:
  comparison_list:
    - prompt1
    - prompt2
    - prompt3
  comparator: sum_equals
  value: 100
```

Here, I would be conveying that `prompt1`, `prompt2`, and `prompt3` all need to sum to 100. The relevant operation for the comparison list is `sum`, and the comparator to use is `equals`.

You could also extend the other logic/comparisons, such as `greaterThan`:
```
promptName:
  comparison_list:
    - prompt1
    - prompt2
    - prompt3
  comparator: sum_greaterThan
  value: 100
```
