### ISSUE TITLE
Update display component to use `reference` syntax

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#810]
We should change the syntax for display elements from:
```yaml
- type: display
  promptName: individualOpenResponse
  position: 1
```
to reflect the new `reference` syntax used by conditions:
```yaml
- type: display
  reference: prompt.individualOpenResponse
  position: 1
```
