### ISSUE TITLE
[Bug]: Numbers don't work as template values

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#892]
### What happened?

this template won't populate properly
```
- template: observerOwnTeamStage
        fields:
          name: "observerOwnTeam_Round_${d0}"
          outcomeFile: observe_agent_success
        broadcast:
          d0:
            - recallIndex: 3
            - recallIndex: 1
            - recallIndex: 5
```
but this will:
```
- template: observerOwnTeamStage
        fields:
          name: "observerOwnTeam_Round_${d0}"
          outcomeFile: observe_agent_success
        broadcast:
          d0:
            - recallIndex: "3"
            - recallIndex: "1"
            - recallIndex: "5"
```

### What browsers do you see the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### What operating system do you see the problem on?

- [ ] Windows
- [ ] Mac
- [ ] Linux

### How did we discover the bug?

- [ ] Reported by participant
- [ ] Observed on Sentry
- [X] Found in dev

### Priority

Inconvenience for researchers
