### ISSUE TITLE
[Bug]: equal, doesnotEqual has string/number issue

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#929]
### What happened?

A condition like this will cause problems:
```
              conditions:
                - reference: survey.partyAffiliation.result.normPosition
                  comparator: doesNotEqual
                  value: 0.5
```
because normPosition is reported as a string, and the value is a float. they won't evaluate the same, even if the string value is "0.5"

### What browsers do you see the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### What operating system do you see the problem on?

- [X] Windows
- [X] Mac
- [X] Linux

### How did we discover the bug?

- [ ] Reported by participant
- [ ] Observed on Sentry
- [X] Found in dev

### Priority

Blocking a specific study
