### ISSUE TITLE
[FEATURE]: use other references in RHS of comparator

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#975]
### User Story

As an experiment designer, I want to be able to use other reference values in the "value" element of a condition, so that I can compare participants' responses with other values they (or their group mates) have entered during the experiment.

### Feature description

A way to specify other reference values in the manifest file, in the 'value' side of a condition

### What would this feature enable?

This would allow use cases such as ensuring that the participant has entered unique values for a series of text entry boxes, or see if they give a consistent response to a prompt if it has been asked multiple times in the study.

### Is this a front end or back end feature?

- [ ] Front end
- [x] Back end

### Priority

None

### Syntax Suggestion

The conditions block, eg:
```
  conditions:
    - reference: prompt.multipleChoiceIntroExample
      comparator: equals
      value: Markdown
```
should be able to use a reference in the "value" argument. 
```
  conditions:
    - reference: prompt.multipleChoiceIntroExample
      comparator: equals
      value: prompt.multipleChoiceIntroExample2
```
A possible extension would be to allow arrays of references on the RHS
```
  conditions:
    - reference: prompt.multipleChoiceIntroExample
      comparator: isOneOf
      value: [prompt.multipleChoiceIntroExample2, prompt.multipleChoiceIntroExample3]
```

Finally, it might be swell to be able to get values from other players as well?
```
  conditions:
    - reference: prompt.multipleChoiceIntroExample
      comparator: equals
      value: p1.prompt.multipleChoiceIntroExample2
```
