### ISSUE TITLE
[FEATURE]: Add contentType field to template definition

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#977]
### User Story

As a developer writing zod validators for treatment files, I want to be able to tell what validator I should use to validate the contents of a template, so that I can make sure that the error messages are correct and useful for that content type

### Feature description

Add a `contentType` field to the structure for a template:
```
 - templateName: topicCondition
    contentType: <XXX> 
    templateContent:
      reference: prompt.${topicName}_presurvey
      comparator: exists
```

When we validate `templateSchema`, use contentType to figure out what validator to use for the `templateContent`

Need to identify what goes in the <XXX>? what do we call these. 

### What would this feature enable?

Better validation and easier treatment development

### Is this a front end or back end feature?

- [ ] Front end
- [x] Back end

### Priority

Makes it easier for researchers to create experiments

### Syntax Suggestion

Something like:
